"""Add barcode to Product model

Revision ID: be1e392c7251
Revises: 
Create Date: 2025-10-11 21:43:39.678665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1e392c7251'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.Column('CategoryName', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('CategoryID'),
    sa.UniqueConstraint('CategoryName')
    )
    op.create_table('Customers',
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.Text(), nullable=True),
    sa.Column('RegistrationDate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('CustomerID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Suppliers',
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('SupplierName', sa.String(length=255), nullable=False),
    sa.Column('ContactName', sa.String(length=100), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('Address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SupplierID'),
    sa.UniqueConstraint('SupplierName')
    )
    op.create_table('Users',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=100), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('Role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('Products',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('ProductName', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('CategoryID', sa.Integer(), nullable=True),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('StockQuantity', sa.Integer(), nullable=False),
    sa.Column('Barcode', sa.String(length=100), nullable=True),
    sa.Column('SupplierID', sa.Integer(), nullable=True),
    sa.Column('LastUpdated', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['CategoryID'], ['Categories.CategoryID'], ),
    sa.ForeignKeyConstraint(['SupplierID'], ['Suppliers.SupplierID'], ),
    sa.PrimaryKeyConstraint('ProductID'),
    sa.UniqueConstraint('Barcode'),
    sa.UniqueConstraint('ProductName')
    )
    op.create_table('PurchaseOrders',
    sa.Column('PO_ID', sa.Integer(), nullable=False),
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('OrderDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('TotalCost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['SupplierID'], ['Suppliers.SupplierID'], ),
    sa.PrimaryKeyConstraint('PO_ID')
    )
    op.create_table('Sales',
    sa.Column('SaleID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=True),
    sa.Column('SaleDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('TotalAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('PaymentMethod', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customers.CustomerID'], ),
    sa.PrimaryKeyConstraint('SaleID')
    )
    op.create_table('InventoryLogs',
    sa.Column('LogID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('SaleID', sa.Integer(), nullable=True),
    sa.Column('ChangeDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('ChangeType', sa.String(length=50), nullable=False),
    sa.Column('QuantityChange', sa.Integer(), nullable=False),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.ForeignKeyConstraint(['SaleID'], ['Sales.SaleID'], ),
    sa.PrimaryKeyConstraint('LogID')
    )
    op.create_table('PurchaseOrderDetails',
    sa.Column('PODetail_ID', sa.Integer(), nullable=False),
    sa.Column('PO_ID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('CostPerItem', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['PO_ID'], ['PurchaseOrders.PO_ID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.PrimaryKeyConstraint('PODetail_ID')
    )
    op.create_table('SaleDetails',
    sa.Column('SaleDetailID', sa.Integer(), nullable=False),
    sa.Column('SaleID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('TotalPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.ForeignKeyConstraint(['SaleID'], ['Sales.SaleID'], ),
    sa.PrimaryKeyConstraint('SaleDetailID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SaleDetails')
    op.drop_table('PurchaseOrderDetails')
    op.drop_table('InventoryLogs')
    op.drop_table('Sales')
    op.drop_table('PurchaseOrders')
    op.drop_table('Products')
    op.drop_table('Users')
    op.drop_table('Suppliers')
    op.drop_table('Customers')
    op.drop_table('Categories')
    # ### end Alembic commands ###
